# @package _global_
defaults:
  - default
  - /collator@datamodule.dataset_managers.train.lm.collator:  infill_dreamon
  - /collator@datamodule.dataset_managers.val.lm.collator: infill_dreamon
  - /datasets@datamodule.dataset_managers.train.lm: opencoder_train
  - /datasets@datamodule.dataset_managers.val.lm: opencoder_val
  - /collator@datamodule.dataset_managers.test.humaneval_infill_prediction.collator: humaneval_infill_pred_dreamon
  - /datasets@datamodule.dataset_managers.test.humaneval_infill_prediction: humaneval_infill_test

datamodule:
  print_batch_fn: dream.datamodule_dream.print_batch_dream
  dataset_managers:
    test:
      humaneval_infill_prediction:
        load_func_kwargs:
          benchmark_name: test

tags:
  dataset: opencoder_dreamon

