# @package _global_
defaults:
  - default
  - /collator@datamodule.dataset_managers.train.lm.collator: seq2seq_mlm
  - /collator@datamodule.dataset_managers.val.lm.collator: seq2seq_mlm
  - /collator@datamodule.dataset_managers.val.prediction.collator: seq2seq_pred_mlm
  - /datasets@datamodule.dataset_managers.train.lm: tinygsm_train
  - /datasets@datamodule.dataset_managers.val.lm: tinygsm_val
  - /datasets@datamodule.dataset_managers.val.prediction: tinygsm_val_pred
  - /datasets@datamodule.dataset_managers.test.gsm8k_prediction: gsm8k_test_pred
  - /collator@datamodule.dataset_managers.test.gsm8k_prediction.collator: seq2seq_pred_mlm

datamodule:
  print_batch_fn: mlm.datamodule_mlm.print_batch_mlm
  dataset_managers:
    train:
      lm:
        collator:
          add_bos: false
    val:
      lm:
        collator:
          add_bos: false
      prediction:
        collator:
          add_bos: false
    test:
      gsm8k_prediction:
        collator:
          add_bos: false

tags:
  dataset: tinygsm
