# @package _global_
defaults:
  - default
  - /datasets@datamodule.dataset_managers.train.lm: iwslt14_de_en_rdm_train
  - /datasets@datamodule.dataset_managers.val.lm: iwslt14_de_en_rdm_val
  - /datasets@datamodule.dataset_managers.val.prediction: iwslt14_de_en_rdm_val_pred
  - /datasets@datamodule.dataset_managers.test.lm: iwslt14_de_en_rdm_test
  - /datasets@datamodule.dataset_managers.test.prediction: iwslt14_de_en_rdm_test_pred
  - /datasets@datamodule.dataset_managers.predict.prediction: iwslt14_de_en_rdm_test_pred
  - /tokenizer@global_components.tokenizer: iwslt14_joint_char_bpe_v1

per_device_batch_size: 32
global_batch_size: 512
block_size: 128
input_block_size: 128

tags:
  dataset: iwslt14_de_en_rdm_v1
