# @package _global_
defaults:
  - default
  - /collator@datamodule.dataset_managers.train.lm.collator: seq2seq_bd3lm
  - /collator@datamodule.dataset_managers.val.lm.collator: seq2seq_bd3lm
  - /collator@datamodule.dataset_managers.test.lm.collator: seq2seq_bd3lm
  - /collator@datamodule.dataset_managers.val.prediction.collator: seq2seq_pred_bd3lm
  - /collator@datamodule.dataset_managers.test.prediction.collator: seq2seq_pred_bd3lm
  - /collator@datamodule.dataset_managers.predict.prediction.collator: seq2seq_pred_bd3lm

datamodule:
  print_batch_fn: bd3lm.datamodule_bd3lm.print_batch_bd3lm

tags:
  dataset: ???
