# @package _global_
defaults:
  - override /callbacks: debug_v2
  - override /loggers: debug

paths:
  log_dir: ${paths.root_dir}/debug_logs/

num_dataset_workers: 1 # does not accept 0
global_batch_size: 1
num_dataloader_workers: 0
per_device_batch_size: 1
dataloader_prefetch_factor: null
dataloader_persistent_workers: False


trainer:
  log_every_n_steps: 1
  limit_train_batches: 1
  limit_val_batches: 1
  limit_test_batches: 1

datamodule:
  dataset_managers:
    val:
      math500_prediction:
        full_name: HuggingFaceH4/MATH-500/test[:1]
        preprocess_function_kwargs:
          num_fewshot: 1
        load_from_cache_file: false
    test:
      math500_prediction:
        full_name: HuggingFaceH4/MATH-500/test[:1]
        preprocess_function_kwargs:
          num_fewshot: 1
        load_from_cache_file: false

