_target_: dream.dream_model.DreamBackbone
config:
  _target_: dream.configuration_dream.DreamConfig
  # Aligned with https://huggingface.co/Dream-org/Dream-v0-Instruct-7B/blob/main/config.json
  vocab_size: 152064
  hidden_size: 3584
  intermediate_size: 18944
  num_hidden_layers: 28
  num_attention_heads: 28
  num_key_value_heads: 4
  hidden_act: silu
  max_position_embeddings: 131072
  initializer_range: 0.02
  rms_norm_eps: 1e-6
  use_cache: true
  tie_word_embeddings: false
  rope_theta: 1000000.0
  use_sliding_window: false
  sliding_window: 4096
  max_window_layers: 28
  attention_dropout: 0.0
  mask_token_id: 151666
  pad_token_id: 151643
  bos_token_id: 151643
  eos_token_id: 151643
