# @package _global_
defaults:
  - owt
  - /collator@datamodule.dataset_managers.train.lm.collator: default_arlm
  - /collator@datamodule.dataset_managers.val.lm.collator: default_arlm
  - /collator@datamodule.dataset_managers.val.unconditional_prediction.collator: unconditional_pred_arlm
  - /collator@datamodule.dataset_managers.test.unconditional_prediction.collator: unconditional_pred_arlm
  - /collator@datamodule.dataset_managers.predict.unconditional_prediction.collator: unconditional_pred_arlm

datamodule:
  print_batch_fn: arlm.datamodule_arlm.print_batch_arlm
  dataset_managers:
    train:
      lm:
        make_infinite: true
    val:
      unconditional_prediction:
        dataset_constructor_str: arlm.datamodule_arlm.ARLMEmptyDataset
    test:
      unconditional_prediction:
        dataset_constructor_str: arlm.datamodule_arlm.ARLMEmptyDataset
    predict:
      unconditional_prediction:
        dataset_constructor_str: arlm.datamodule_arlm.ARLMEmptyDataset

tags:
  dataset: owt 