defaults:
  - gram_graph_coloring_train_8v
  - _self_

_target_: xlm.datamodule.DatasetManager
full_name: brozonoyer/gram-graph-coloring/test
full_name_debug: brozonoyer/gram-graph-coloring/train
stages:
  - fit
  - validate
dataloader_kwargs:
  batch_size: ${per_device_val_batch_size}
  drop_last: false
