defaults:
  - gram_n_queens_train_8x8
  - _self_

_target_: xlm.datamodule.DatasetManager
full_name: brozonoyer/gram-n-queens/test
full_name_debug: brozonoyer/gram-n-queens/train
stages:
  - fit
  - validate
dataloader_kwargs:
  batch_size: ${per_device_val_batch_size}
  drop_last: false
