defaults:
  - iwslt14_de_en_rdm

full_name: local/iwslt14_de_en_rdm_text_v1/validation
full_name_debug: local/iwslt14_de_en_rdm_text_v1/train
load_kwargs:
  data_files: ${oc.env:IWSLT14_RDM_TEXT_ROOT}/validation.parquet
stages:
  - fit
  - validate
dataloader_kwargs:
  shuffle: false
  drop_last: False
