defaults:
  - default_text

_target_: xlm.datamodule.DatasetManager
collator: ???
full_name: HuggingFaceH4/MATH-500/test
full_name_debug: HuggingFaceH4/MATH-500/test
preprocess_function: xlm.tasks.math500.math500_preprocess_fn
on_the_fly_processor: null
on_the_fly_group_processor: null
columns_to_remove: null
columns_to_keep:
  - prompt_ids
  - target_ids
  - answer
stages: ???
iterable_dataset_shards: null
shuffle_buffer_size: null
shuffle_seed: 42
split_by_node: true
dataloader_kwargs:
    batch_size: ${per_device_batch_size}
    num_workers: ${num_dataloader_workers}
    shuffle: false
    pin_memory: True
    persistent_workers: False
    prefetch_factor: ${dataloader_prefetch_factor}
    drop_last: False
model_name: null
