defaults:
  - tinygsm_local_sample

preprocess_function: xlm.tasks.tinygsm.tinygsm_pred_preprocess_fn
preprocess_function_kwargs:
  sep: "\n"
columns_to_remove:
  - question
  - code
stages:
  - fit
  - validate
  - predict
