_target_: xlm.tasks.owt.generative_perplexity_post_hoc.GenerativePerplexityPostHocEval
default_judge_device: cuda
judge_devices: null
metric_prefix: ""
evaluators:
  gpt2-small:
    _target_: xlm.generative_perplexity.AutoModelForCausalLMGenerativePerplexityEvaluator
    name: gpt2
    batch_size: 64
    max_length: 1024
