_target_: gemma_usdm.datamodule_gemma_usdm.GemmaUsdmTrainCollator
input_block_size: ${input_block_size}
block_size: ${block_size}
tokenizer: ${global_components:tokenizer}
add_bos: ${oc.select:add_bos,false}
add_eos: ${oc.select:add_eos,true}
truncate: block
loss_on_padding: ${oc.select:loss_on_padding,true}
